name: Format and Push with Biome and Prettier

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile

      - name: Run TypeScript type check
        run: yarn type:check

      - name: Run Biome formatter
        run: yarn run biome:format

      - name: Run Prettier formatter
        run: yarn run format:imports

      - name: Check for changes
        id: git_diff
        run: |
          git diff --exit-code || echo "::set-output name=changes::changes"

      - name: Commit and push changes if any
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply formatting with Biome and Prettier"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
