name: Delete Merged Branch

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  delete-merged-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Delete merged branch
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          echo "Branch to delete: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" != "master" && "$BRANCH_NAME" != "main" ]]; then
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} --delete "$BRANCH_NAME"
          else
            echo "Skipping deletion of protected branch: $BRANCH_NAME"
          fi

