name: Format Code with Prettier

on:
  pull_request: 

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier to format code
        run: npm run format

      - name: Check for changes
        id: git_diff
        run: |
          git diff --exit-code || echo "::set-output name=changes::changes"

      - name: Commit and push changes if any
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply formatting with Prettier"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
